"""empty message

Revision ID: 0c7268c3dbef
Revises: 9290e9291598
Create Date: 2023-11-29 07:49:16.099051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c7268c3dbef'
down_revision = '9290e9291598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.drop_column('redesSociales_twitter_alt')
        batch_op.drop_column('teEsperamos_alt')
        batch_op.drop_column('comunicate_alt')
        batch_op.drop_column('contactos_reunionVirtual_alt')
        batch_op.drop_column('garantias_alt')
        batch_op.drop_column('redesSociales_instagram_alt')
        batch_op.drop_column('cta_alt')
        batch_op.drop_column('logo_alt')
        batch_op.drop_column('redesSociales_facebook_alt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redesSociales_facebook_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('cta_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_instagram_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('garantias_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_reunionVirtual_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('comunicate_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('teEsperamos_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_twitter_alt', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
