"""empty message

Revision ID: 2a1baed1ad00
Revises: bc1380d590d2
Create Date: 2023-11-29 07:53:57.596898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a1baed1ad00'
down_revision = 'bc1380d590d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reunion_virtual_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reunion_virtual_link', sa.String(length=255), nullable=True))
        batch_op.drop_column('reunionVirtual_image')
        batch_op.drop_column('reunionVirtual_link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reunionVirtual_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('reunionVirtual_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('reunion_virtual_link')
        batch_op.drop_column('reunion_virtual_image')

    # ### end Alembic commands ###
