"""empty message

Revision ID: 9290e9291598
Revises: 8426d1164337
Create Date: 2023-11-29 07:40:23.602425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9290e9291598'
down_revision = '8426d1164337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreDelProyecto', sa.String(length=255), nullable=True),
    sa.Column('header_link1', sa.String(length=255), nullable=True),
    sa.Column('header_image1', sa.String(length=255), nullable=True),
    sa.Column('header_alt1', sa.String(length=255), nullable=True),
    sa.Column('header_link2', sa.String(length=255), nullable=True),
    sa.Column('header_image2', sa.String(length=255), nullable=True),
    sa.Column('header_alt2', sa.String(length=255), nullable=True),
    sa.Column('header_link3', sa.String(length=255), nullable=True),
    sa.Column('header_image3', sa.String(length=255), nullable=True),
    sa.Column('header_alt3', sa.String(length=255), nullable=True),
    sa.Column('cta_image', sa.String(length=255), nullable=True),
    sa.Column('cta_link', sa.String(length=255), nullable=True),
    sa.Column('cta_alt', sa.String(length=255), nullable=True),
    sa.Column('garantias_image', sa.String(length=255), nullable=True),
    sa.Column('garantias_link', sa.String(length=255), nullable=True),
    sa.Column('garantias_alt', sa.String(length=255), nullable=True),
    sa.Column('comunicate_image', sa.String(length=255), nullable=True),
    sa.Column('comunicate_link', sa.String(length=255), nullable=True),
    sa.Column('comunicate_alt', sa.String(length=255), nullable=True),
    sa.Column('contactos_whatsapp_image', sa.String(length=255), nullable=True),
    sa.Column('contactos_whatsapp_number', sa.String(length=255), nullable=True),
    sa.Column('contactos_whatsapp_alt', sa.String(length=255), nullable=True),
    sa.Column('contactos_mail_image', sa.String(length=255), nullable=True),
    sa.Column('contactos_mail_address', sa.String(length=255), nullable=True),
    sa.Column('contactos_mail_alt', sa.String(length=255), nullable=True),
    sa.Column('contactos_reunionVirtual_image', sa.String(length=255), nullable=True),
    sa.Column('contactos_reunionVirtual_link', sa.String(length=255), nullable=True),
    sa.Column('contactos_reunionVirtual_alt', sa.String(length=255), nullable=True),
    sa.Column('teEsperamos_image', sa.String(length=255), nullable=True),
    sa.Column('teEsperamos_link', sa.String(length=255), nullable=True),
    sa.Column('teEsperamos_alt', sa.String(length=255), nullable=True),
    sa.Column('textoLegal_link', sa.String(length=255), nullable=True),
    sa.Column('textoLegal_text', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_facebook_image', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_facebook_link', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_facebook_alt', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_twitter_image', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_twitter_link', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_twitter_alt', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_instagram_image', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_instagram_link', sa.String(length=255), nullable=True),
    sa.Column('redesSociales_instagram_alt', sa.String(length=255), nullable=True),
    sa.Column('logo_image', sa.String(length=255), nullable=True),
    sa.Column('logo_link', sa.String(length=255), nullable=True),
    sa.Column('logo_alt', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.drop_table('email')
    # ### end Alembic commands ###
