"""empty message

Revision ID: bc1380d590d2
Revises: 0c7268c3dbef
Create Date: 2023-11-29 07:51:02.877037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bc1380d590d2'
down_revision = '0c7268c3dbef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_alt', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mail_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mail_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mail_alt', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reunionVirtual_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reunionVirtual_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('facebook_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twitter_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('instagram_image', sa.String(length=255), nullable=True))
        batch_op.drop_column('redesSociales_twitter_image')
        batch_op.drop_column('contactos_reunionVirtual_link')
        batch_op.drop_column('redesSociales_instagram_link')
        batch_op.drop_column('redesSociales_facebook_link')
        batch_op.drop_column('contactos_mail_alt')
        batch_op.drop_column('logo_link')
        batch_op.drop_column('contactos_whatsapp_number')
        batch_op.drop_column('redesSociales_instagram_image')
        batch_op.drop_column('contactos_whatsapp_alt')
        batch_op.drop_column('redesSociales_twitter_link')
        batch_op.drop_column('contactos_reunionVirtual_image')
        batch_op.drop_column('redesSociales_facebook_image')
        batch_op.drop_column('contactos_mail_address')
        batch_op.drop_column('contactos_whatsapp_image')
        batch_op.drop_column('contactos_mail_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contactos_mail_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_whatsapp_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_mail_address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_facebook_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_reunionVirtual_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_twitter_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_whatsapp_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_instagram_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_whatsapp_number', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('logo_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_mail_alt', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_facebook_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_instagram_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('contactos_reunionVirtual_link', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('redesSociales_twitter_image', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('instagram_image')
        batch_op.drop_column('twitter_image')
        batch_op.drop_column('facebook_image')
        batch_op.drop_column('reunionVirtual_link')
        batch_op.drop_column('reunionVirtual_image')
        batch_op.drop_column('mail_alt')
        batch_op.drop_column('mail_address')
        batch_op.drop_column('mail_image')
        batch_op.drop_column('whatsapp_alt')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('whatsapp_image')

    # ### end Alembic commands ###
